/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Color;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import owncode.DBconnector;


/**
 *
 * @author Gayathree Rajakaruna
 */
public class addlecturer extends javax.swing.JInternalFrame {
    
    
    Connection con = null;
    PreparedStatement pst = null;
    
    int id=0;
    
  
    

    /**
     * Creates new form addlecturer
     */
    public addlecturer() {
        initComponents();
        
        //connect to DB
        con = DBconnector.connect();
    }
    
    public void stafID()
        {
    }
    
    
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        stfidbox = new javax.swing.JTextField();
        snamebox = new javax.swing.JTextField();
        facbox = new javax.swing.JComboBox<>();
        depbox = new javax.swing.JComboBox<>();
        cenbox = new javax.swing.JComboBox<>();
        bulbox = new javax.swing.JComboBox<>();
        rnkbox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        levbox = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("ADD LECTURERS");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 13)); // NOI18N
        jLabel2.setText("STAFF ID");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 13)); // NOI18N
        jLabel3.setText("NAME");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 13)); // NOI18N
        jLabel4.setText("FACULTY");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 13)); // NOI18N
        jLabel5.setText("DEPARTMENT");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 13)); // NOI18N
        jLabel6.setText("CENTER");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 13)); // NOI18N
        jLabel7.setText("BUILDING");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 13)); // NOI18N
        jLabel8.setText("LEVEL");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 13)); // NOI18N
        jLabel9.setText("RANK");

        stfidbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stfidboxActionPerformed(evt);
            }
        });
        stfidbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stfidboxKeyPressed(evt);
            }
        });

        snamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameboxActionPerformed(evt);
            }
        });

        facbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Faculty", "Faculty of Computing", "Faculty of Engineering", "Faculty of Business", "Faculty of Humanities and Sciences", "Faculty of Graduate studied and Research", "School of Architecture", "SLIIT Academy", "SLIIT International" }));

        depbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Department", "Department of Computer Science & Software Engineering", "Department of Computer Systems Engineering", "Department of Business Management", "Department of Civil Engineering", "Department of Electrical & Computer Engineering", "Department of Humanities and Sciencies", " " }));

        cenbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Center", "Malabe", "Metro", "Matara", "Kandy", "Kurunegala", "Jaffna" }));
        cenbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cenboxActionPerformed(evt);
            }
        });

        bulbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Building", "Main Building", "New Building", "Engineering Building", "Bussienss Faculty Building", "Humanities & Science Building", "Other" }));

        rnkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnkboxActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setText("Generate Rank");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 13)); // NOI18N
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        clearbutton.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 13)); // NOI18N
        clearbutton.setText("CLEAR");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });

        levbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select level", "Professor", "Assistant Professor", "Senior Lecturer(HG)", "Senior Lecturer", "Lecturer", "Assistant Lecturer", " " }));
        levbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rnkbox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(levbox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bulbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cenbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(depbox, 0, 1, Short.MAX_VALUE)
                            .addComponent(facbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(snamebox)
                            .addComponent(stfidbox)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(clearbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(stfidbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(snamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(facbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(depbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cenbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bulbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(levbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rnkbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void snameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameboxActionPerformed

    private void rnkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnkboxActionPerformed

       
        // TODO add your handling code here:
    }//GEN-LAST:event_rnkboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String stid = stfidbox.getText();
        String stname = snamebox.getText();
        String facl = facbox.getSelectedItem().toString();
        String dept = depbox.getSelectedItem().toString();
        String cent = cenbox.getSelectedItem().toString();
        String buld = bulbox.getSelectedItem().toString();
        String lev = levbox.getSelectedItem().toString();
        String rak = rnkbox.getText();
        
        
        try {
            
            String q = "INSERT INTO lecturers (staffid,name,faculty,department,center,building,level,rank) values('"+ stid +"','"+ stname +"','"+ facl +"','"+ dept +"','"+ cent +"','"+ buld +"','"+ lev +"','"+ rak +"')";
            pst = con.prepareStatement(q);
            pst.execute();
            
            
           
            
        } 
        catch (Exception e) 
        {
            System.out.println(e);
        }
        
        stfidbox.setText(" ");
        snamebox.setText("");
        facbox.setSelectedIndex(0);
        depbox.setSelectedIndex(0);
        cenbox.setSelectedIndex(0);
        bulbox.setSelectedIndex(0);
        levbox.setSelectedIndex(0);
        rnkbox.setText(" ");
        
        
        
        
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cenboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cenboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cenboxActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        stfidbox.setText(" ");
        snamebox.setText("");
        facbox.setSelectedIndex(0);
        depbox.setSelectedIndex(0);
        cenbox.setSelectedIndex(0);
        bulbox.setSelectedIndex(0);
        levbox.setSelectedIndex(0);
        rnkbox.setText(" ");
        
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void stfidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stfidboxActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_stfidboxActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(levbox.getSelectedItem().equals("Professor")){

           rnkbox.setText(1+"."+stfidbox.getText());
    
        }else if (levbox.getSelectedItem().equals("Assistant Professor")) {
                
            rnkbox.setText(2+"."+stfidbox.getText());
            
        } else if (levbox.getSelectedItem().equals("Senior Lecturer(HG)")) {
             
            rnkbox.setText(3+"."+stfidbox.getText());
            
        }else if (levbox.getSelectedItem().equals("Senior Lecturer")) {
             
            rnkbox.setText(4+"."+stfidbox.getText());
            
        }else if (levbox.getSelectedItem().equals("Lecturer")) {
             
            rnkbox.setText(5+"."+stfidbox.getText());
            
        }else if(levbox.getSelectedItem().equals("Assistant Lecturer")) {
             
            rnkbox.setText(6+"."+stfidbox.getText());
            
        }
        
        


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void levboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levboxActionPerformed
//     if(levbox.getSelectedItem().equals("Professor")){
////      stfidbox.getText();
//
//    
//            
//     
//         
//     }else if (levbox.getSelectedItem().equals("Assistant Professor")) {
//            
//        } else if (levbox.getSelectedItem().equals("Senior Lecturer(HG)")) {
//            
//        }else if (levbox.getSelectedItem().equals("Senior Lecturer")) {
//            
//        }else if (levbox.getSelectedItem().equals("Lecturer")) {
//            
//        }else if(levbox.getSelectedItem().equals("Assistant Lecturer")) {
//            
//        }
       
    }//GEN-LAST:event_levboxActionPerformed

    private void stfidboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stfidboxKeyPressed
        // TODO add your handling code here:
        
        String stfid = stfidbox.getText();
        if(stfid.matches("^[0-9]*$") && stfid.length()==5){
            
            stfidbox.setBackground(Color.white);
        
        }else{
            stfidbox.setBackground(new Color(255,102,102));
        }
        
        
    }//GEN-LAST:event_stfidboxKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bulbox;
    private javax.swing.JComboBox<String> cenbox;
    private javax.swing.JButton clearbutton;
    private javax.swing.JComboBox<String> depbox;
    private javax.swing.JComboBox<String> facbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> levbox;
    private javax.swing.JTextField rnkbox;
    private javax.swing.JTextField snamebox;
    private javax.swing.JTextField stfidbox;
    // End of variables declaration//GEN-END:variables
}
