/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Arrays;
import javax.swing.JOptionPane;
import mycode.DBconnect;
import net.proteanit.sql.DbUtils;
import java.util.List;

/**
 *
 * @author official
 */
public class AddStudentsgroups extends javax.swing.JInternalFrame {
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null; 

    /**
     * Creates new form AddStudentsgroups
     */
    public AddStudentsgroups() {
        initComponents();
        
         //connection for DB
        con = DBconnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addstudentgroupcombo = new javax.swing.JComboBox<>();
        addstudentprogrammecombo = new javax.swing.JComboBox<>();
        addgroupnumbercombo = new javax.swing.JComboBox<>();
        addsubgroupscombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        studentGroupID = new javax.swing.JTextField();
        subgroupID = new javax.swing.JTextField();
        generateID = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Academic year/Semester");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Programme");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Group Number");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Sub Group Number");

        addstudentgroupcombo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        addstudentgroupcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Y1.S1", "Y1.S2", "Y2.S1", "Y2.S2", "Y3.S1", "Y3.S2", "Y4.S1", "Y4.S2" }));
        addstudentgroupcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentgroupcomboActionPerformed(evt);
            }
        });

        addstudentprogrammecombo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        addstudentprogrammecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "IT", "CSSE", "CSE", "IM", "SE" }));

        addgroupnumbercombo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        addgroupnumbercombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", " " }));
        addgroupnumbercombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addgroupnumbercomboActionPerformed(evt);
            }
        });

        addsubgroupscombo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        addsubgroupscombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7", "8", " " }));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Group ID");

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Sub Group ID");

        studentGroupID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        subgroupID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        generateID.setBackground(new java.awt.Color(153, 153, 153));
        generateID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        generateID.setText("Generate ID's");
        generateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateIDActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Add Student Groups");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addgroupnumbercombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addstudentgroupcombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addstudentprogrammecombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addsubgroupscombo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(studentGroupID, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(subgroupID)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(321, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(405, 405, 405))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(generateID)
                        .addGap(452, 452, 452))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addstudentgroupcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(addstudentprogrammecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addgroupnumbercombo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addsubgroupscombo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel5)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentGroupID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(subgroupID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(generateID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addgroupnumbercomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addgroupnumbercomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addgroupnumbercomboActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String addstudentyearsemester = addstudentgroupcombo.getSelectedItem().toString();
        String addstudentprogramme = addstudentprogrammecombo.getSelectedItem().toString();
        String addstudentgroupnumber = addgroupnumbercombo.getSelectedItem().toString();
        String addstudentsubgroup = addsubgroupscombo.getSelectedItem().toString();
        
                List<String> SgroupID = Arrays.asList(addstudentyearsemester, addstudentprogramme, addstudentgroupnumber);
                String disgroupID = String.join(". ", SgroupID);
                //studentGroupID.setText(disgroupID);

                List<String> SSubgroupID = Arrays.asList(addstudentyearsemester, addstudentprogramme, addstudentgroupnumber, addstudentsubgroup);
                String dissubgroupID = String.join(". ", SSubgroupID);
                //subgroupID.setText(dissubgroupID);
                
            try {
                
                String g = "INSERT INTO studentgroups(yearsemester,studentprogramme ,groupnumber,subgroup,StudentGroupID,StudentSubgroupID) VALUES ('"+ addstudentyearsemester +"',"
                        + " '"+ addstudentprogramme +"', '"+ addstudentgroupnumber +"', '"+ addstudentsubgroup + "','"+ disgroupID+"','"+ dissubgroupID +"')";
                pst = con.prepareStatement(g);
                pst.execute();

                grouptableload();

            }

            catch (Exception e) {
                       System.out.println(e);
            }  
            
            JOptionPane.showMessageDialog(null, "The Student group was added successfully.");
    }//GEN-LAST:event_jButton2ActionPerformed

    public void generateID(){
             
        String yearsemester = addstudentgroupcombo.getSelectedItem().toString();
        String studentprogramme = addstudentprogrammecombo.getSelectedItem().toString();
        String groupnumber = addgroupnumbercombo.getSelectedItem().toString();
        String subgroup = addsubgroupscombo.getSelectedItem().toString();
                 
                List<String> SgroupID = Arrays.asList(yearsemester, studentprogramme, groupnumber);
                String disgroupID = String.join(". ", SgroupID);
                studentGroupID.setText(disgroupID);

                List<String> SSubgroupID = Arrays.asList(yearsemester, studentprogramme, groupnumber, subgroup);
                String dissubgroupID = String.join(". ", SSubgroupID);
                subgroupID.setText(dissubgroupID);       
                      
    }

    private void clearTesxtAddgrouop() {        
        
        addstudentgroupcombo.setSelectedItem(null);
        addstudentprogrammecombo.setSelectedItem(null);
        addgroupnumbercombo.setSelectedItem(null);
        addsubgroupscombo.setSelectedItem(null);
        studentGroupID.setText(null);
        subgroupID.setText(null);
      
    }
    
    private void addstudentgroupcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentgroupcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addstudentgroupcomboActionPerformed

    private void generateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateIDActionPerformed
        generateID();
    }//GEN-LAST:event_generateIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        clearTesxtAddgrouop();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> addgroupnumbercombo;
    private javax.swing.JComboBox<String> addstudentgroupcombo;
    private javax.swing.JComboBox<String> addstudentprogrammecombo;
    private javax.swing.JComboBox<String> addsubgroupscombo;
    private javax.swing.JButton generateID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField studentGroupID;
    private javax.swing.JTextField subgroupID;
    // End of variables declaration//GEN-END:variables

    private void grouptableload() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
