/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import Interfaces.ParallelSession;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import mycode.DBconnect;
import net.proteanit.sql.DbUtils;
import mycode.DBconnect;
/**
 *
 * @author official
 */
public class consecutiveSessions extends javax.swing.JInternalFrame {
            
            Connection con = null;
            PreparedStatement pst = null;
            ResultSet rs = null; 
            Statement stmt = null;
            
    /**
     * Creates new form consecutiveSessions
     */
    public consecutiveSessions() {
        initComponents();
        
        con = DBconnect.connect();
        sessiontableload();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ConsecutiveTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ConSearch = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        ConsecutiveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ConsecutiveTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsecutiveTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ConsecutiveTable);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Add Consecutive");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Delete Concesutive");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("View Consecutive");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Consecutive Sessions");

        ConSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Search here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(416, 416, 416)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ConSearch)
                                .addGap(18, 18, 18)))
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ConSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsecutiveTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsecutiveTableMouseClicked
        
        int row = ConsecutiveTable.getSelectedRow();
        
        String sid = ConsecutiveTable.getValueAt(row, 0).toString();
        String firstLecturer = ConsecutiveTable.getValueAt(row, 1).toString();
        String secondLecturer = ConsecutiveTable.getValueAt(row, 2).toString();
        String tag = ConsecutiveTable.getValueAt(row, 3).toString();
        String subjectCode = ConsecutiveTable.getValueAt(row, 4).toString();      
        String subjectName = ConsecutiveTable.getValueAt(row, 5).toString();
        String studentGroup = ConsecutiveTable.getValueAt(row, 6).toString();
        String numberOfStudents = ConsecutiveTable.getValueAt(row, 7).toString();
        String duration = ConsecutiveTable.getValueAt(row, 8).toString();
        String day = ConsecutiveTable.getValueAt(row, 9).toString();
        
    }//GEN-LAST:event_ConsecutiveTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int row = ConsecutiveTable.getSelectedRow();
        
        String sid = ConsecutiveTable.getValueAt(row, 0).toString();
        String firstLecturer = ConsecutiveTable.getValueAt(row, 1).toString();
        String secondLecturer = ConsecutiveTable.getValueAt(row, 2).toString();
        String tag = ConsecutiveTable.getValueAt(row, 3).toString();
        String subjectCode = ConsecutiveTable.getValueAt(row, 4).toString();      
        String subjectName = ConsecutiveTable.getValueAt(row, 5).toString();
        String studentGroup = ConsecutiveTable.getValueAt(row, 6).toString();
        String numberOfStudents = ConsecutiveTable.getValueAt(row, 7).toString();
        String duration = ConsecutiveTable.getValueAt(row, 8).toString();
        String day = ConsecutiveTable.getValueAt(row, 9).toString();
        
            try {
                
                String g = "INSERT INTO consecutive(sid,firstLecturer,secondLecturer,tag,subjectCode,subjectName,studentGroup, numberOfStudents, duration, day ) VALUES ('"+ sid +"','"+firstLecturer +"', '"+ secondLecturer +"', '"+ tag +"', '"+ subjectCode +"','"+ subjectName +"',"
                        + "'"+ studentGroup +"','"+ numberOfStudents +"', '"+ duration +"', '"+ day +"')";
                pst = con.prepareStatement(g);
                pst.execute();           
            }

            catch (Exception e) {
                       System.out.println(e);
            }
            
            JOptionPane.showMessageDialog(null, "The consecutive session was added successfully.");
                                                                                           
                                           
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    public void contableload() {
          
            try {
            String session = "SELECT sid,firstLecturer,secondLecturer,tag,subjectCode,subjectName,studentGroup,numberOfStudents,duration,day FROM consecutive";
            pst = con.prepareStatement(session);
            rs = pst.executeQuery();

            ConsecutiveTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            }
          
           catch (Exception e) {
                System.out.println(e);
            }   
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int condelete = JOptionPane.showConfirmDialog(null, "Do you want to delete this consecutive session?");
        
        int row = ConsecutiveTable.getSelectedRow();
        
        String sid = ConsecutiveTable.getValueAt(row, 0).toString();
         
                try {
                    
                  String sql = "DELETE from consecutive where sid = '"+ sid +"'";
                  pst = con.prepareStatement(sql);
                  pst.execute();

                  contableload();

                  }

                  catch (Exception e) {
                      System.out.println(e);
                  }        
          
               
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       contableload();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        String subjectName = ConSearch.getText();
        
        String consecutivesearch = "SELECT sid,firstLecturer,secondLecturer,tag,subjectCode,subjectName,studentGroup,numberOfStudents,duration,day FROM sessions WHERE subjectName = '"+ subjectName +"'";
        
        try {
        pst = con.prepareStatement(consecutivesearch);
        rs = pst.executeQuery();
        
        ConsecutiveTable.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        
        catch (Exception e) {
          
        }
    }//GEN-LAST:event_jButton4ActionPerformed

public void sessiontableload() {
        //DefaultTableModel mo = (DefaultTableModel)nonparalleltable.getModel();
           //mo.addRow(new Object[] {false, "data1","data2","data3"});
           
           
            try {
            String session = "SELECT sid,firstLecturer,secondLecturer,tag,subjectCode,subjectName,studentGroup,numberOfStudents,duration,day FROM sessions";
            pst = con.prepareStatement(session);
            rs = pst.executeQuery();

            ConsecutiveTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            }
          
           catch (Exception e) {
                System.out.println(e);
            }   
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ConSearch;
    private javax.swing.JTable ConsecutiveTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
