/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import mycode.DBconnect;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author official
 */
public class Managestudentgroups extends javax.swing.JInternalFrame {
    
    Connection con = null;
    PreparedStatement pst,pst1 = null;
    ResultSet rs = null; 

    /**
     * Creates new form Managestudentgroups
     */
    public Managestudentgroups() {
        initComponents();
        
        //connection for DB
        con = DBconnect.connect();
        
        grouptableload(); //load table
        
        
        
    }
    
    public void grouptableload() {
        
            try {
            String sql = "SELECT groupID,yearsemester,studentprogramme,groupnumber,subgroup,StudentGroupID,StudentSubGroupID FROM studentgroups";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            managestudenttable.setModel(DbUtils.resultSetToTableModel(rs));              
            
            }

            catch (Exception e) {
                System.out.println(e);
            }   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        managestudenttable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        managegroupid = new javax.swing.JTextField();
        managesubid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        managestudentcombo = new javax.swing.JComboBox<>();
        manageprogrammecombo = new javax.swing.JComboBox<>();
        managestudentgroupnumbercombo = new javax.swing.JComboBox<>();
        managestudentsubcombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        groupIDs = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        managestudenttable.setAutoCreateRowSorter(true);
        managestudenttable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        managestudenttable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        managestudenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        managestudenttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managestudenttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(managestudenttable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Academic year/sememster");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Programme");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Sub Group Number");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Group ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Sub Group ID");

        managegroupid.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        managesubid.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Group Number");

        managestudentcombo.setEditable(true);
        managestudentcombo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        managestudentcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Y1.S1", "Y1.S2", "Y2.S1", "Y2.S2", "Y3.S1", "Y3.S2", "Y4.S1", "Y4.S2" }));
        managestudentcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managestudentcomboActionPerformed(evt);
            }
        });

        manageprogrammecombo.setEditable(true);
        manageprogrammecombo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        manageprogrammecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "IT", "CSSE", "CSE", "IM", "SE" }));

        managestudentgroupnumbercombo.setEditable(true);
        managestudentgroupnumbercombo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        managestudentgroupnumbercombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", " " }));

        managestudentsubcombo.setEditable(true);
        managestudentsubcombo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        managestudentsubcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        groupIDs.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText("ID ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setText("Manage Student Groups");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel3)
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(groupIDs, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(876, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(380, 380, 380))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(managestudentcombo, 0, 138, Short.MAX_VALUE)
                            .addComponent(manageprogrammecombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(managestudentgroupnumbercombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(managestudentsubcombo, 0, 135, Short.MAX_VALUE)
                            .addComponent(managegroupid)
                            .addComponent(managesubid)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(60, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(groupIDs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(managestudentcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageprogrammecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(managestudentgroupnumbercombo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(managestudentsubcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(managegroupid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(managesubid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(83, 83, 83)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void managestudenttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managestudenttableMouseClicked
        
        int row = managestudenttable.getSelectedRow();
        
        String groupID = managestudenttable.getValueAt(row, 0).toString();
        String yearsemester = managestudenttable.getValueAt(row, 1).toString();
        String studentprogramme = managestudenttable.getValueAt(row, 2).toString();
        String groupnumber = managestudenttable.getValueAt(row, 3).toString();
        String subgroup = managestudenttable.getValueAt(row, 4).toString();      
        String StudentGroupID = managestudenttable.getValueAt(row, 5).toString();
        String StudentSubGroupID = managestudenttable.getValueAt(row, 6).toString();  
        
        groupIDs.setText(groupID);
        managestudentcombo.setSelectedItem(yearsemester);
        manageprogrammecombo.setSelectedItem(studentprogramme);
        managestudentgroupnumbercombo.setSelectedItem(groupnumber);
        managestudentsubcombo.setSelectedItem(subgroup);
        managegroupid.setText(StudentGroupID);
        managesubid.setText(StudentSubGroupID);
        
    }//GEN-LAST:event_managestudenttableMouseClicked

    private void clearTestfield(){
        
        groupIDs.setText(null);
        managestudentcombo.setSelectedItem(null);
        manageprogrammecombo.setSelectedItem(null);
        managestudentgroupnumbercombo.setSelectedItem(null);
        managestudentsubcombo.setSelectedItem(null);
        managegroupid.setText(null);
        managesubid.setText(null);
       
    }
    
    private void managestudentcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managestudentcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managestudentcomboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             
        int studentupdate = JOptionPane.showConfirmDialog(null, "Do you really want to update?");
             
             if(studentupdate == 0){
                 
                 String groupID = groupIDs.getText();
                 String yearsemester = managestudentcombo.getSelectedItem().toString();
                 String studentprogramme = manageprogrammecombo.getSelectedItem().toString();
                 String groupnumber = managestudentgroupnumbercombo.getSelectedItem().toString();
                 String subgroup = managestudentsubcombo.getSelectedItem().toString();
                 String StudentGroupID = managegroupid.getText();
                 String StudentSubGroupID = managesubid.getText();    
                 
                    try {
                    String sql = "UPDATE studentgroups SET yearsemester = '"+ yearsemester +"', studentprogramme = '"+studentprogramme+"', groupnumber = '"+ groupnumber +"', subgroup = '"+ subgroup +"'"
                            + " where groupID = '"+ groupID +"' ";
                            
                           List<String> SgroupID = Arrays.asList(yearsemester, studentprogramme,groupnumber);
                           String disgroupID = String.join(". ", SgroupID);
                           managegroupid.setText(disgroupID);

                           List<String> SSubgroupID = Arrays.asList(yearsemester, studentprogramme, groupnumber, subgroup);
                           String dissubgroupID = String.join(". ", SSubgroupID);
                           managesubid.setText(dissubgroupID);
                    
                    String sql2 = "UPDATE studentgroups SET StudentGroupID = '"+ disgroupID +"', StudentSubGroupID ='"+dissubgroupID+"' "; 
                    pst = con.prepareStatement(sql);
                    pst1 = con.prepareStatement(sql2);
                    pst.execute();
                    pst1.execute();
                                    
                    grouptableload(); //load table
                    
                    }

                    catch (Exception e) {
                           System.out.println(e);

                    }            
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int tagsdelete = JOptionPane.showConfirmDialog(null, "Do you want to delete this?");
        
            String groupID = groupIDs.getText();
         
                try {
                    
                  String sql = "DELETE from studentgroups where groupID = '"+ groupID +"'";
                  pst = con.prepareStatement(sql);
                  pst.execute();

                  grouptableload();

                  }

                  catch (Exception e) {
                      System.out.println(e);
                  }        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                
            clearTestfield();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel groupIDs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField managegroupid;
    private javax.swing.JComboBox<String> manageprogrammecombo;
    private javax.swing.JComboBox<String> managestudentcombo;
    private javax.swing.JComboBox<String> managestudentgroupnumbercombo;
    private javax.swing.JComboBox<String> managestudentsubcombo;
    private javax.swing.JTable managestudenttable;
    private javax.swing.JTextField managesubid;
    // End of variables declaration//GEN-END:variables

    private void tableload() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
