/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.sql.Connection;
import java.sql.PreparedStatement;
import mycode.DBconnect;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author official
 */
public class ManageTags extends javax.swing.JInternalFrame {
           
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null; 

    /**
     * Creates new form ManageTags
     */
    public ManageTags() {
        initComponents();
        
        //connection for DB
        con = DBconnect.connect();
        
        tableload(); //load table      
    }
    
    public void tableload() {
        
        try {
        String sql = "SELECT tagid,tagname,tagcode,relatedtag FROM tags";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        
        managetagstable.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        
        catch (Exception e) {
            System.out.println(e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        managetagstable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        managetagName = new javax.swing.JTextField();
        managetagCode = new javax.swing.JTextField();
        manageRelatedtag = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tagsupdatebutton = new javax.swing.JButton();
        tagidlabel = new javax.swing.JLabel();
        tagsDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        managetagstable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        managetagstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        managetagstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managetagstableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(managetagstable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Tag Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Tag Code");

        managetagName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        managetagCode.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        managetagCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managetagCodeActionPerformed(evt);
            }
        });

        manageRelatedtag.setEditable(true);
        manageRelatedtag.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        manageRelatedtag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Lecture", "Tutorial", "Practical" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Related Tag");

        tagsupdatebutton.setBackground(new java.awt.Color(153, 153, 153));
        tagsupdatebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tagsupdatebutton.setText("Update");
        tagsupdatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagsupdatebuttonActionPerformed(evt);
            }
        });

        tagidlabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        tagsDelete.setBackground(new java.awt.Color(153, 153, 153));
        tagsDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tagsDelete.setText("Delete");
        tagsDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagsDeleteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Manage Tags");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("ID");

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tagsDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tagsupdatebutton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addGap(35, 35, 35)
                        .addComponent(tagidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(manageRelatedtag, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managetagCode, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managetagName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(394, 394, 394))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tagsupdatebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(tagsDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tagidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managetagName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(managetagCode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageRelatedtag, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void managetagstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managetagstableMouseClicked
        
        int row = managetagstable.getSelectedRow();
        
        String tagid = managetagstable.getValueAt(row, 0).toString();
        String tagname = managetagstable.getValueAt(row, 1).toString();
        String tagcode = managetagstable.getValueAt(row, 2).toString();
        String relatedtag = managetagstable.getValueAt(row, 3).toString();
         
        tagidlabel.setText(tagid);
        managetagName.setText(tagname);
        managetagCode.setText(tagcode);
        manageRelatedtag.setSelectedItem(relatedtag);
       
    }//GEN-LAST:event_managetagstableMouseClicked

    private void managetagCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managetagCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managetagCodeActionPerformed

    private void tagsupdatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagsupdatebuttonActionPerformed
        
        int tagupdate = JOptionPane.showConfirmDialog(null, "Do you really want to update?");
             
             if(tagupdate == 0){
                 
                 String tagid = tagidlabel.getText();
                 String tagname = managetagName.getText();
                 String tagcode = managetagCode.getText();
                 String relatedtag = manageRelatedtag.getSelectedItem().toString();
                 
                    try {
                    String sql = "UPDATE tags SET tagname = '"+ tagname +"', tagcode = '"+ tagcode +"', relatedtag = '"+ relatedtag +"' where tagid = '"+ tagid +"' ";
                                     
                    pst = con.prepareStatement(sql);
                    pst.execute();

                    tableload(); //load table
                    }

                    catch (Exception e) {
                           System.out.println(e);

                    }
    }//GEN-LAST:event_tagsupdatebuttonActionPerformed

    }
    
    private void clearmanagetags(){
        
            tagidlabel.setText(null);
            managetagName.setText(null);
            managetagCode.setText(null);
            manageRelatedtag.setSelectedItem(null);
    
    }
    
    private void tagsDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagsDeleteActionPerformed
           
        int tagsdelete = JOptionPane.showConfirmDialog(null, "Do you want to delete this?");
            
            String tagid = tagidlabel.getText();
            
                try {
                String sql = "DELETE from tags where tagid = '"+ tagid +"'";
                pst = con.prepareStatement(sql);
                pst.execute();

                tableload();

                }

                catch (Exception e) {
                    System.out.println(e);
                }           
            
    }//GEN-LAST:event_tagsDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        clearmanagetags();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> manageRelatedtag;
    private javax.swing.JTextField managetagCode;
    private javax.swing.JTextField managetagName;
    private javax.swing.JTable managetagstable;
    private javax.swing.JLabel tagidlabel;
    private javax.swing.JButton tagsDelete;
    private javax.swing.JButton tagsupdatebutton;
    // End of variables declaration//GEN-END:variables
}
