/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import mycode.DBconnect;             
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;


/**
 *
 * @author official
 */
public class ParallelSession extends javax.swing.JInternalFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null; 
    
    /**
     * Creates new form ParallelSession
     */
    public ParallelSession() {
        
        initComponents();
         
        con = DBconnect.connect();
         
        sessiontableload();    
    }
    
    public void sessiontableload() {
       
            try {
            String session = "SELECT sid,firstLecturer,secondLecturer,tag,subjectCode,subjectName,studentGroup,numberOfStudents,duration,day FROM sessions";
            pst = con.prepareStatement(session);
            rs = pst.executeQuery();

            ParallelTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            }
          
           catch (Exception e) {
                System.out.println(e);
            }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ParallelTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ParallelSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        ParallelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ParallelTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ParallelTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ParallelTable);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Add Parallel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("View All Parallel Sessions");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("Delete Parallel Sessions");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Parallel Sessions");

        ParallelSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Search ");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ParallelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton4)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280))))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(109, 109, 109)
                .addComponent(jButton3)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ParallelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ParallelTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParallelTableMouseClicked
          
        int row = ParallelTable.getSelectedRow();
        
        String sid = ParallelTable.getValueAt(row, 0).toString();
        String firstLecturer = ParallelTable.getValueAt(row, 1).toString();
        String secondLecturer = ParallelTable.getValueAt(row, 2).toString();
        String tag = ParallelTable.getValueAt(row, 3).toString();
        String subjectCode = ParallelTable.getValueAt(row, 4).toString();      
        String subjectName = ParallelTable.getValueAt(row, 5).toString();
        String studentGroup = ParallelTable.getValueAt(row, 6).toString();
        String numberOfStudents = ParallelTable.getValueAt(row, 7).toString();
        String duration = ParallelTable.getValueAt(row, 8).toString();
        String day = ParallelTable.getValueAt(row, 9).toString();
                              
    }//GEN-LAST:event_ParallelTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int row = ParallelTable.getSelectedRow();
        
        String sid = ParallelTable.getValueAt(row, 0).toString();
        String firstLecturer = ParallelTable.getValueAt(row, 1).toString();
        String secondLecturer = ParallelTable.getValueAt(row, 2).toString();
        String tag = ParallelTable.getValueAt(row, 3).toString();
        String subjectCode = ParallelTable.getValueAt(row, 4).toString();      
        String subjectName = ParallelTable.getValueAt(row, 5).toString();
        String studentGroup = ParallelTable.getValueAt(row, 6).toString();
        String numberOfStudents = ParallelTable.getValueAt(row, 7).toString();
        String duration = ParallelTable.getValueAt(row, 8).toString();
        String day = ParallelTable.getValueAt(row, 9).toString();
        
            try {
                
                String g = "INSERT INTO nonparallel(sid,firstLecturer,secondLecturer,tag,subjectCode,subjectName,studentGroup, numberOfStudents, duration, day ) VALUES ('"+ sid +"','"+firstLecturer +"', '"+ secondLecturer +"', '"+ tag +"', '"+ subjectCode +"','"+ subjectName +"',"
                        + "'"+ studentGroup +"','"+ numberOfStudents +"', '"+ duration +"', '"+ day +"')";
                pst = con.prepareStatement(g);
                pst.execute();

             
            }

            catch (Exception e) {
                       System.out.println(e);
            }
            
            JOptionPane.showMessageDialog(null, "The Parallel Session was added successfully.");
                                                                                           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         ParallelLoad();   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        int sessiondelete = JOptionPane.showConfirmDialog(null, "Do you want to delete this parallel session?");
        
        int row = ParallelTable.getSelectedRow();
        
        String sid = ParallelTable.getValueAt(row, 0).toString();
         
                try {
                    
                  String sql = "DELETE from nonparallel where sid = '"+ sid +"'";
                  pst = con.prepareStatement(sql);
                  pst.execute();

                  ParallelLoad();

                  }

                  catch (Exception e) {
                      System.out.println(e);
                  }        
                                            

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         
        String subjectName = ParallelSearch.getText();
        
        String parasearch = "SELECT sid,firstLecturer,secondLecturer,tag,subjectCode,subjectName,studentGroup,numberOfStudents,duration,day FROM sessions WHERE subjectName = '"+ subjectName +"'";
        
        try {
        pst = con.prepareStatement(parasearch);
        rs = pst.executeQuery();
        
        ParallelTable.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        
        catch (Exception e) {
          System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

     public void ParallelLoad() {
       
           
            try {
            String session = "SELECT sid,firstLecturer,secondLecturer,tag,subjectCode,subjectName,studentGroup,numberOfStudents,duration,day FROM nonparallel";
            pst = con.prepareStatement(session);
            rs = pst.executeQuery();

            ParallelTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            }
          
           catch (Exception e) {
                System.out.println(e);
            }   
    }
    
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ParallelSearch;
    private javax.swing.JTable ParallelTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
