/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import owncode.DBconnector;

/**
 *
 * @author Gayathree Rajakaruna
 */
public class selectlecturersandtag extends javax.swing.JInternalFrame {
    
    
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs, rs2;
    Statement stm ,stm2;
    String name;
    

    /**
     * Creates new form selectlecturersandtag
     */
    public selectlecturersandtag() {
        initComponents();
        
        
        //connect to DB
        con = DBconnector.connect();
        
        selectLecturer2();
        selectLecturer1();
        selectSubjectName();
        selectGroup();
        selectSubjectCode();
        //selectTag();
        
    }
    
    public void selectLecturer1(){

         try {
            stm = con.createStatement();
            
             rs = stm.executeQuery("select name from lecturers");
           
            while(rs.next()){
                
                String name = rs.getString("name");
                 sl1.addItem(name);
                 
              
            }
            } catch (Exception e) {
        }
      
    }
    public void selectLecturer2(){
        
         try {
            stm = con.createStatement();
            
             rs = stm.executeQuery("select name from lecturers");
           
            while(rs.next()){
                
                String name = rs.getString("name");
                 sl2.addItem(name);
                 
              
            }
            } catch (Exception e) {
        }
    }
    public void selectSubjectName(){
        
        try {
             stm = con.createStatement();
            
            rs = stm.executeQuery("select subname from subjects");
            
            while(rs.next()){
                String subname = rs.getString("subname");
                ssn1.addItem(subname);
                
            }
            
            
            
        } catch (Exception e) {
        }
        
    }
     public void selectSubjectCode(){
         
         try {
             stm = con.createStatement();
            
            rs = stm.executeQuery("select subcode from subjects");
            
            while(rs.next()){
                String subcode = rs.getString("subcode");
                ssc1.addItem(subcode);
                
            }
            
            
            
        } catch (Exception e) {
        }
        
    }
      public void selectGroup(){
        try {
             stm = con.createStatement();
            
            rs = stm.executeQuery("select StudentGroupID,StudentSubGroupID from studentgroups");
            
            while(rs.next()){
                
                String StudentGroupID = rs.getString("StudentGroupID");
                ssg1.addItem(StudentGroupID);
                
                String StudentSubGroupID = rs.getString("StudentSubGroupID");
                ssg1.addItem(StudentSubGroupID);
                
            }
            
            
            
        } catch (Exception e) {
        }
    }
//      public void selectTag(){
//           try {
//             stm = con.createStatement();
//            
//            rs = stm.executeQuery("select relatedtag from tags");
//            
//            while(rs.next()){
//                String relatedtag = rs.getString("relatedtag");
//                st3.addItem(relatedtag);
//                
//            }
//            
//            
//            
//        } catch (Exception e) {
//        }
//      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sl1 = new javax.swing.JComboBox<>();
        st3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        sl2 = new javax.swing.JComboBox<>();
        jTextLectureName1 = new javax.swing.JTextField();
        jTextLecture2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ssc1 = new javax.swing.JComboBox<>();
        ssn1 = new javax.swing.JComboBox<>();
        ssg1 = new javax.swing.JComboBox<>();
        nstudent1 = new javax.swing.JTextField();
        duration = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("SELECT LECTURERS & TAG");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Select Lecturer (1):");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Selected Lecturer(s):");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Select Tag:");

        sl1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select lecturer name" }));
        sl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sl1MouseClicked(evt);
            }
        });
        sl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sl1ActionPerformed(evt);
            }
        });

        st3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Tag", "Lecture", "Tutorial", "Practicle" }));
        st3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                st3MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Select Lecturer (2):");

        sl2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select lecturer name", "-" }));
        sl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sl2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sl2MousePressed(evt);
            }
        });
        sl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sl2ActionPerformed(evt);
            }
        });

        jTextLectureName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLectureName1ActionPerformed(evt);
            }
        });

        jLabel6.setText("1)");

        jLabel7.setText("2)");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Select Subject Code:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Select Subject Name:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Select Group:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Number of  Students:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Duration:");

        ssc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject code" }));
        ssc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ssc1MouseClicked(evt);
            }
        });

        ssn1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject name" }));
        ssn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ssn1MouseClicked(evt);
            }
        });
        ssn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssn1ActionPerformed(evt);
            }
        });

        ssg1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Student group" }));
        ssg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ssg1MouseClicked(evt);
            }
        });

        jLabel13.setText("hrs");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("SELECT GROUP & SUBJECT");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(sl2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(370, 370, 370)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel12)))
                                    .addComponent(jLabel14))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ssg1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextLectureName1)
                                        .addComponent(jTextLecture2)
                                        .addComponent(st3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ssc1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ssn1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nstudent1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(duration, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(sl1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(227, 227, 227))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextLectureName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLecture2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(st3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(53, 53, 53)
                .addComponent(jLabel14)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ssn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ssg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(nstudent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sl1MouseClicked
  


    }//GEN-LAST:event_sl1MouseClicked

    private void sl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sl1ActionPerformed
   
 
        String lecName1;
        
               lecName1 =sl1.getSelectedItem().toString();
        if (sl1.getSelectedIndex()!=0){
             
             jTextLectureName1.setText(lecName1);
         }else{
              jTextLectureName1.setText("");
         }
            
    }//GEN-LAST:event_sl1ActionPerformed

    private void sl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sl2MouseClicked
       
     
    }//GEN-LAST:event_sl2MouseClicked

    private void sl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sl2ActionPerformed
        
        String lecName2;
        
         lecName2=sl2.getSelectedItem().toString();
         if (sl2.getSelectedIndex()!=0){
             
             jTextLecture2.setText(lecName2);
         }else{
              jTextLecture2.setText("");
         }
            

      
    }//GEN-LAST:event_sl2ActionPerformed

    private void st3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_st3MouseClicked

       
        
    }//GEN-LAST:event_st3MouseClicked

    private void jTextLectureName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLectureName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLectureName1ActionPerformed

    private void sl2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sl2MousePressed

           
        // TODO add your handling code here:
    }//GEN-LAST:event_sl2MousePressed

    private void ssn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssn1ActionPerformed

    private void ssc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssc1MouseClicked
         
    }//GEN-LAST:event_ssc1MouseClicked

    private void ssn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssn1MouseClicked
         
    }//GEN-LAST:event_ssn1MouseClicked

    private void ssg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssg1MouseClicked
        
    }//GEN-LAST:event_ssg1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String slec1 = sl1.getSelectedItem().toString();
        String slec2 = sl2.getSelectedItem().toString();
//        String slec1 = jTextLectureName1.getText();
//        String slec2 = jTextLecture2.getText();

        String stag=""; 
        if(st3.getSelectedItem().equals("Lecture")) {
            stag="Lecture";
        }else if(st3.getSelectedItem().equals("Practicle")) {
            stag="Practicle";
        }else if(st3.getSelectedItem().equals("Tutorial")) {
            stag="Tutorial";
        }else if(st3.getSelectedItem().equals("")) {
            stag="Tuorial";
        }
        
        String ssubc = ssc1.getSelectedItem().toString();
        String ssubn = ssn1.getSelectedItem().toString();
        String sgrp = ssg1.getSelectedItem().toString();
        String nstu = nstudent1.getText();
        String dura = duration.getText();
        
        try {
            
            String q = "INSERT INTO sessions (firstLecturer,secondLecturer,tag,subjectCode,subjectName,studentGroup,numberOfStudents,duration) values('"+ slec1 +"','"+ slec2 +"','"+ stag +"','"+ ssubc +"','"+ ssubn +"','"+ sgrp +"','"+ nstu +"','"+ dura +"')";
            pst = con.prepareStatement(q);
            pst.execute();
            
            
           
            
        } 
        catch (Exception e) 
        {
            System.out.println(e);
        }
        
        sl1.setSelectedIndex(0);
        sl2.setSelectedIndex(0);
        jTextLectureName1.setText("");
        jTextLecture2.setText("");
        st3.setSelectedIndex(0);
        ssc1.setSelectedIndex(0);
        ssn1.setSelectedIndex(0);
        ssg1.setSelectedIndex(0);
        nstudent1.setText("");
        duration.setText("");
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        sl1.setSelectedIndex(0);
        sl2.setSelectedIndex(0);
        jTextLectureName1.setText("");
        jTextLecture2.setText("");
        st3.setSelectedIndex(0);
        ssc1.setSelectedIndex(0);
        ssn1.setSelectedIndex(0);
        ssg1.setSelectedIndex(0);
        nstudent1.setText("");
        duration.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField duration;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextLecture2;
    private javax.swing.JTextField jTextLectureName1;
    private javax.swing.JTextField nstudent1;
    private javax.swing.JComboBox<String> sl1;
    private javax.swing.JComboBox<String> sl2;
    private javax.swing.JComboBox<String> ssc1;
    private javax.swing.JComboBox<String> ssg1;
    private javax.swing.JComboBox<String> ssn1;
    private javax.swing.JComboBox<String> st3;
    // End of variables declaration//GEN-END:variables
}
